[package]
name = "avrth"
version = "0.0.1"
authors = ["Andreas Rottmann <a.rottmann@gmx.at>"]
license = "GPL-3.0-or-later"
keywords = ["forth"]

[dependencies]
structopt = "0.2"
failure = "0.1.2"
num-traits = "0.2.5"
byteorder = "1.2.6"
