[package]
name = "avrth-asm"
version = "0.0.1"
authors = ["Andreas Rottmann <mail@r0tty.org>"]
license = "GPL-3.0-or-later"
keywords = ["assembler", "avr"]
edition = "2021"

[dependencies]
combine = "4.5.2"
anyhow = "1.0.42"
structopt = "0.3.22"
env_logger = "0.10.0"
